### PR TITLE
Updated most of the parts to PHP 8 v2

### PR DESCRIPTION
**Pull request by JosunLP**
Revised code related to sockets to run with PHP 8

### CODE REVIEW

**Comment by JosunLP** [comment]
@danopia will you take a look at this?

**Comment by JosunLP** [comment]
@danopia should be final now

**Comment by danopia** [comment]
Any idea what the minimum compatible PHP version would be now? I assume that some of the new stuff is more recently added to the language

**Comment by JosunLP** [comment]
Since we work with the new Socket Objects that got introduced in 8.0 i assume thats the minimum required version.

**Comment by danopia** [comment]
ok, I'll take this today and also document that in the README, thanks for the extended efforts to repair my old bad code

**Comment by JosunLP** [comment]
Im happy to help ^^

**Pull request merged**
